[package]
name = "pipeline"
version = "0.1.0"
authors = ["Alexander Seppälä <dev@timot.se>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.102", features = ["derive"]}
ron = "0.5.1"
uuid = {version = "0.8.1", features = ["v4"]}
handlebars = "3.0.0-beta.1"
