[package]
name = "job"
version = "0.1.0"
authors = ["Alexander Seppälä <dev@timot.se>"]
edition = "2018"

[lib]
name = "job"
path = "src/lib.rs"

[dependencies]
pipeline = {path = "../pipeline"}
handlebars = "3.0.0-beta.1"
serde_json = "1.0.40"
serde = {version = "1.0.91", features = ["derive"]}
