[package]
name = "runner"
version = "0.1.0"
authors = ["Alexander Seppälä <dev@timot.se>"]
edition = "2018"

[lib]
name = "runner"
path = "src/lib.rs"

[dependencies]
pipeline = {path = "../pipeline"}
uuid = {version = "0.7.4", features = ["v4"]}
handlebars = "2.0.1"
derivative = "1.0.2"
